### ISSUE TITLE
Questions about what the indicators represent

### ISSUE THREAD

**Issue by Aichiniuroumian** [DUT-lujunyu/ToxiCN_MM#1]
Hi, Junyu, 

this is an amazing work and makes a landmark contribution to the detection and Identification of Chinese memes. When I was studying this code, I'm a little confused about what each metric represents in the output of the code. I hope you could help answer them:
1) When performing the harmful meme detection task, there are two values ​​in the all_f1 list. Which value does F1Harm take in the paper?
2) there are five values ​​in the all_f1 list when performing the harmful type identification task. In the paper, which value is taken for F1Tg., F1Off., F1Sex, and F1Disp. respectively? Or what do each of the 5 values in all_f1 mean?

Looking forward to your early reply~ Have a nice day! 😊

**Comment by DUT-lujunyu** [comment]
您好，您的邮件已经收到，谢谢

**Comment by DUT-lujunyu** [comment]
Thank you for your interest in our work.

Task 1 is a binary classification task aimed at determining whether a meme is harmful, where F1_Harm represents the F1-score for harmful memes.
Task 2 is a five-class classification task designed to identify specific harmful types, with index 0 representing the non-harmful category. Given that the model’s detection performance may vary across categories, we provide an F1 list storing the F1-score for each category. Specifically, F1_Tg., F1_Off., F1_Sex., and F1_Disp. correspond to the F1-scores for the four harmful types.

For details on the calculation of these metrics, please refer to the `get_scores()` function in `train_eval_.py`.

If you have any further questions, please feel free to ask at any time.

**Comment by Aichiniuroumian** [comment]
Thank you very much for your enthusiastic reply, my concern has been solved, thanks again~😊
